---
- name: Set /bin/server.sh variables
  ansible.builtin.lineinfile:
    path: /tmp/onedev-7.7.11/bin/server.sh
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    mode: '755'
  loop:
    - { regexp: '^APP_NAME=', line: 'APP_NAME="{{ onedev_bin_server_app_name }}"' }
    - { regexp: '^APP_LONG_NAME=', line: 'APP_LONG_NAME="{{ onedev_bin_server_app_long_name }}"' }
    - { regexp: '^WRAPPER_CMD=', line: 'WRAPPER_CMD="{{ onedev_bin_server_wrapper_cmd }}"' }
    - { regexp: '^WRAPPER_CONF=', line: 'WRAPPER_CONF="{{ onedev_bin_server_wrapper_conf }}"' }
    - { regexp: '^PRIORITY=', line: 'PRIORITY={{ onedev_bin_server_priority }}' }
    - { regexp: '^PIDDIR=', line: 'PIDDIR="{{ onedev_bin_server_piddir }}"' }
    - { regexp: '^PIDFILE_CHECK_PID=', line: 'PIDFILE_CHECK_PID={{ onedev_bin_server_pidfile_check_pid }}' }
    - { regexp: '^WAIT_AFTER_STARTUP=', line: 'WAIT_AFTER_STARTUP={{ onedev_bin_server_wait_after_startup }}' }
    - { regexp: '^WAIT_FOR_STARTED_STATUS=', line: 'WAIT_FOR_STARTED_STATUS={{ onedev_bin_server_wait_for_started_status }}' }
    - { regexp: '^WAIT_FOR_STARTED_TIMEOUT=', line: 'WAIT_FOR_STARTED_TIMEOUT={{ onedev_bin_server_wait_for_started_timeout }}' }
    - { regexp: '^#DETAIL_STATUS=', line: 'DETAIL_STATUS={{ onedev_bin_server_detail_status }}' }
    - { regexp: '^#PAUSABLE=', line: 'PAUSABLE={{ onedev_bin_server_pausable }}' }
    - { regexp: '^#PAUSABLE_MODE=', line: 'PAUSABLE_MODE={{ onedev_bin_server_pausable_mode }}' }
    - { regexp: '^#RUN_AS_USER=', line: 'RUN_AS_USER={{ onedev_bin_server_run_as_user }}' }
    - { regexp: '^#SU_OPTS=', line: 'SU_OPTS="{{ onedev_bin_server_su_opts }}"' }
    - { regexp: '^#BRIEF_USAGE=', line: 'BRIEF_USAGE={{ onedev_bin_server_brief_usage }}' }
    - { regexp: '^SERVICE_MANAGEMENT_TOOL=', line: 'SERVICE_MANAGEMENT_TOOL={{ onedev_bin_server_service_management_tool }}' }
    - { regexp: '^SYSTEMD_KILLMODE=', line: 'SYSTEMD_KILLMODE={{ onedev_bin_server_systemd_killmode }}' } 
    - { regexp: '^PLIST_DOMAIN=', line: 'PLIST_DOMAIN={{ onedev_bin_server_plist_domain }}' }
    - { regexp: '^MACOSX_KEEP_RUNNING=', line: 'MACOSX_KEEP_RUNNING="{{ onedev_bin_server_macosx_keep_running }}"' }
    - { regexp: '^RUN_LEVEL=', line: 'RUN_LEVEL={{ onedev_bin_server_run_level }}' }
    - { regexp: '^FILES_TO_SOURCE=', line: 'FILES_TO_SOURCE={{ onedev_bin_server_files_to_source }}' }
