---
- name: Ensure APT cache
  apt: 
    update_cache: yes
  changed_when: false

- name: Install onedev required APT packages
  apt: 
    name: "{{ item }}"
    state: present
  loop:
    - default-jre 
    - default-jdk
    - git

- name: Ensure onedev-7.7.11 not already exists
  stat:
    path: "/tmp/onedev-7.7.11"
  register: onedev_directory_exist

- name: Unarchive a file that needs to be downloaded (added in 2.0)
  ansible.builtin.unarchive:
    src: https://code.onedev.io/downloads/projects/160/builds/3112/artifacts/onedev-7.7.11.zip
    dest: /tmp
    remote_src: yes
  when: not onedev_directory_exist.stat.exists

- name: Install & Start onedev service
  command: ./server.sh installstart
  args:
    chdir: /tmp/onedev-7.7.11/bin
