#!/usr/bin/env ansible-playbook
---
- name: Install one-dev baremetal server 
  include: _install_server.yml
  tags: 
    - onedev_install

- name: Uninstall one-dev baremetal server 
  include: _uninstall_server.yml
  tags: 
    - onedev_uninstall
