---
- name: Install one-dev baremetal server 
  include: _install.yml
  tags: 
    - onedev_install

- name: Uninstall one-dev baremetal server 
  include: _uninstall.yml
  tags: 
    - onedev_uninstall
