---
dependencies: []

galaxy_info:
  author: twatel
  description: ansible role onedev for barmetal installation
  company: "myself"
  license: "license (MIT)"
  min_ansible_version: 2.4
  platforms:
    - name: Debian
      versions:
        - 11
  galaxy_tags:
    - system
    - onedev
    - ansible
    - automation
