---

# Onedev server script vars
onedev_bin_server_app_name: "onedev"
onedev_bin_server_app_long_name: "OneDev"
onedev_bin_server_wrapper_cmd: "../boot/wrapper"
onedev_bin_server_wrapper_conf: "../conf/wrapper.conf"
onedev_bin_server_priority: ""
onedev_bin_server_piddir: "."
onedev_bin_server_pidfile_check_pid: "true"
onedev_bin_server_wait_after_startup: "0"
onedev_bin_server_wait_for_started_status: "true"
onedev_bin_server_wait_for_started_timeout: "120"
onedev_bin_server_detail_status: "true"
onedev_bin_server_pausable: "true"
onedev_bin_server_pausable_mode: "signals"
onedev_bin_server_run_as_user: "root"
onedev_bin_server_su_opts: "-s /bin/bash"
onedev_bin_server_brief_usage: "true"
onedev_bin_server_service_management_tool: "auto"
onedev_bin_server_systemd_killmode: "control-group"
onedev_bin_server_plist_domain: "org.tanukisoftware.wrapper"
onedev_bin_server_macosx_keep_running: "false"
onedev_bin_server_run_level: "20"
onedev_bin_server_files_to_source: ""